services:
  weboldal:
    build: ./weboldal
    image: weboldal:1.1
    ports:
      - "8080:8000"
  weboldal2:
    image: weboldal:1.1
    ports:
      - "8081:8000"
    volumes:
      - ./weboldal2:/app
  weboldal3:
    image: weboldal:1.1
    ports:
      - "8082:8000"
    volumes:
      - ./weboldal3:/app
