name: Teszt


on: push

jobs:
  koszones:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: docker compose ps
      - run: ./szkriptek/ellenorzo.sh
      - run: docker compose logs
